services:

  user-service:
    image: user-service:latest
    ports:
      - "8001:8001"
    volumes:
      - user_db_data:/base-microservice/data
      - static_volume:/var/html/static
    env_file:
      - ./microservices/user-service/.env
    environment:
      - STATIC_ROOT=/var/html/static 
      - ADMIN_PASSWORD=/run/secrets/admin_password
      - API_KEY=/run/secrets/api_key
      - SECRET_KEY=/run/secrets/user_secret_key
    secrets:
      - admin_password
      - api_key
      - user_secret_key
    networks:
      - app-network

  db-service:
    image: db-operations-service:latest  
    expose:
      - "8002"
    volumes:
      - ./exported_tables:/base-microservice/exported_tables
    env_file:
      - ./microservices/db-operations-service/.env
    environment: &db_env_vars
      - API_KEY=/run/secrets/api_key
      - CELERY_BROCKER_URL=/run/secrets/celery_brocker_url
      - SECRET_KEY=/run/secrets/db_secret_key
      - DB_URL=/run/secrets/db_url
    secrets: &db_secrets
      - celery_brocker_url
      - api_key
      - db_secret_key
      - db_url
    depends_on:
      db_postgres:
        condition: service_healthy
    networks:
      - app-network

  analytics-service:
    image: analytics-service:latest
    ports:
      - "8003"
    volumes:
      - anal_db_data:/base-microservice/data
    env_file:
      - ./microservices/analytics-service/.env
    environment: &anal_env_vars
      - API_KEY=/run/secrets/api_key
      - SECRET_KEY=/run/secrets/analytics_secret_key
      - CELERY_BROCKER_URL=/run/secrets/celery_brocker_url
    secrets: &anal_secrets
      - api_key
      - analytics_secret_key
      - celery_brocker_url
    depends_on:
      db-service:
        condition: service_healthy
    networks:
      - app-network

  api-gateway:
    image: api-gateway:latest
    expose:
      - "8000"
    env_file:
      - ./api-gateway/.env
    environment:
      - SECRET_KEY=/run/secrets/gate_secret_key
    secrets:
      - gate_secret_key
    depends_on:
      user-service:
        condition: service_healthy
      db-service:
        condition: service_healthy
      analytics-service:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    image: frontend:latest
    expose:
      - "8080"
    depends_on:
      api-gateway:
       condition: service_healthy
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static_volume:/var/html/static 
    depends_on:
      api-gateway:
        condition: service_healthy
    networks:
      - app-network

  celery_worker_db:
    build: ./microservices/db-operations-service
    command: celery -A config worker --loglevel=info -Q db
    volumes:
      - ./exported_tables:/base-microservice/exported_tables 
    env_file:
      - ./microservices/db-operations-service/.env
    environment: *db_env_vars
    secrets: *db_secrets
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  celery_worker_anal:
    build: ./microservices/analytics-service
    command: celery -A config worker --loglevel=info -Q analytics
    volumes:
      - anal_db_data:/base-microservice/data
    env_file:
      - ./microservices/analytics-service/.env
    environment: *anal_env_vars
    secrets: *anal_secrets
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  celery_beat_db:
    build: ./microservices/db-operations-service
    command: celery -A config beat --loglevel=info
    env_file:
      - ./microservices/db-operations-service/.env
    environment: *db_env_vars
    secrets: *db_secrets
    depends_on:
      redis:
        condition: service_healthy
      celery_worker_db:
        condition: service_started
      db-service:
        condition: service_healthy
    networks:
      - app-network

  celery_beat_anal:
    build: ./microservices/analytics-service
    command: celery -A config beat --loglevel=info
    env_file:
      - ./microservices/analytics-service/.env
    environment: *anal_env_vars
    secrets: *anal_secrets
    depends_on:
      redis:
        condition: service_healthy
      celery_worker_anal:
        condition: service_started
      analytics-service:
        condition: service_healthy
    networks:
      - app-network

  db_postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_interval: 10s
      start_period: 20s

  redis:
    image: redis:7-alpine
    command: >
      sh -c 'redis-server --requirepass "$(cat /run/secrets/redis_password)"'
    secrets:
      - redis_password
    ports:
      - "6380:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 10s


volumes:
  user_db_data:
  postgres_data: 
  anal_db_data:
  static_volume:

networks:
  app-network:
    driver: bridge

secrets:
  admin_password:
    file: ./secrets/admin_password.txt
  analytics_secret_key:
    file: ./secrets/analytics_secret_key.txt
  api_key:
    file: ./secrets/api_key.txt
  celery_brocker_url:
    file: ./secrets/celery_brocker_url.txt
  db_secret_key:
    file: ./secrets/db_secret_key.txt
  db_url:
    file: ./secrets/db_url.txt
  gate_secret_key:
    file: ./secrets/gate_secret_key.txt
  user_secret_key:
    file: ./secrets/user_secret_key.txt
  db_password:
    file: ./secrets/db_password.txt
  redis_password:
    file: ./secrets/redis_password.txt
